import pyautogui
import time
pyautogui.PAUSE = 0.08
pyautogui.FAILSAFE = True

time.sleep(12)
pyautogui.write("I just need someone in my life", interval=0.09)
pyautogui.press("enter")
pyautogui.write("To give it structure...", interval=0.09)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(1)
pyautogui.write("To handle all the selfish ways", interval=0.09)
pyautogui.press("enter")
pyautogui.write("I'd spend my time without her", interval=0.08)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(1)
pyautogui.write("You're everything I want", interval=0.09)
pyautogui.press("enter")
pyautogui.write("But I can't deal with all your lovers", interval=0.07)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(0.7)
pyautogui.write("Saying I'm the one", interval=0.08)
pyautogui.press("enter")
pyautogui.write("But it's your actions that speak louder (oh)", interval=0.08)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(1.1)
pyautogui.write("Giving me love when you are down", interval=0.08)
pyautogui.press("enter")
pyautogui.write("And need another", interval=0.08)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(1.8)
pyautogui.write("I've got to get away and let you go (oh)", interval=0.09)
pyautogui.press("enter")
pyautogui.write("I've got to get over", interval=0.09)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(1)
pyautogui.write("But I love you so", interval=0.09)
pyautogui.press("enter")
time.sleep(4.9)
pyautogui.write("I love you so", interval=0.1)
pyautogui.press("enter")
time.sleep(4.9)
pyautogui.write("I love you so", interval=0.1)
pyautogui.press("enter")
time.sleep(4.9)
pyautogui.write("I love you so", interval=0.1)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(2.8)
pyautogui.write("I'm gonna pack my things", interval=0.09)
pyautogui.press("enter")
time.sleep(0.9)
pyautogui.write("And leave you behind", interval=0.09)
pyautogui.press("enter")
time.sleep(0.9)
pyautogui.write("This feeling's old and I know that", interval=0.09)
pyautogui.press("enter")
time.sleep(0.8)
pyautogui.write("I've made up my mind", interval=0.09)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(0.4)
pyautogui.write("I hope you feel what I felt", interval=0.09)
pyautogui.press("enter")

time.sleep(0.9)
pyautogui.write("When you shattered my soul", interval=0.09)
pyautogui.press("enter")

time.sleep(0.4)
pyautogui.write("Cause you were cruel and I'm a fool", interval=0.07)
pyautogui.press("enter")

time.sleep(0.5)
pyautogui.write("So please let me go", interval=0.08)
pyautogui.press("enter")
pyautogui.press("enter")

time.sleep(2)
pyautogui.write("But I love you so (please let me go)", interval=0.08)
pyautogui.press("enter")
time.sleep(3.7)
pyautogui.write("I love you so (please let me go)", interval=0.08)
pyautogui.press("enter")
time.sleep(3.7)
pyautogui.write("I love you so (please let me go)", interval=0.08)
pyautogui.press("enter")
time.sleep(3.7)
pyautogui.write("I love you so", interval=0.08)
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("enter")
